apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-argo
  namespace: argocd
spec:
  destination:
    namespace: kube-argo
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/toleksa/kube-argo'
    targetRevision: $TARGET_REVISION
    path: .
    helm:
      values: |
        domain: $KUBERNETES_DOMAIN
        externaldns:
          rfc2136:
            host: $EXTERNAL_DNS_RFC2136_HOST
            zone: $EXTERNAL_DNS_RFC2136_ZONE
            tsigSecret: $EXTERNAL_DNS_RFC2136_TSIGSECRET 
        metallb:
          pools:
          - name: default
            protocol: layer2
            addresses: 
            - $METALLB_ADDRESSES
            avoid-buggy-ips: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false
