apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: '3.25.2'
    chart: argo-cd
    helm:
      values: |
        server:
          extraArgs:
            - --insecure
          ingress:
            enabled: true
            https: false
            hosts:
            - "argocd.{{ .Values.domain }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
